group/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'group'

urlpatterns = [
    path('', views.ListGroups.as_view(), name = 'all'),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path('post/in/<slug>/', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name = 'leave'),
]

post/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('post/', include('post.urls')),
    path('group/', include('group.urls'))
]

group/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
import misaka
from django.contrib.auth import get_user_model
from django import template
# Create your models here.

User = get_user_model()
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("group:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete = models.DO_NOTHING)
    user = models.ForeignKey(User,related_name='user_groups', on_delete = models.DO_NOTHING)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

group/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.views import generic
from django.shortcuts import get_object_or_404
from group.models import Group, GroupMember
from . import models
# Create your views here.

class CreateGroup(generic.CreateView,LoginRequiredMixin):
    fields = ('name', 'description')
    model = Group


class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("group:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("group:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

group/templates/group/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

group/templates/group/group_detail.html
{% extends "group/group_base.html" %}
{% block pregroup %}
<h1>{{group.name}}</h1>
  <div class="container">
    <div class="row">
      <h2> Member Count: {{group.members.count}}</h2>
      {% if user in group.members.all %}
        <a href="{% url 'group:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning ml-3"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
      {% else %}
        <a href="{% url 'group:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning ml-3"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
      {% endif %}
    </div>
</div>
{% endblock %}
  {% block group_content %}
  <div class="col-md-8">
  	{% if group.posts.count == 0 %}
  	<h2>No posts in this group yet!</h2>
  	{% else %}
  		{% for post in group.posts.all %}
  			{% include "post/_post.html" %}
  		{% endfor %}
  	{% endif %}
  </div>
  {% endblock %}

group/templates/group/group_form.html
{% extends "group/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
<h4>Create A New Group</h4>
<div class="container">
  <form method="POST" action="{% url 'group:create' %}" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}
</div>

group/templates/group/group_list.html
{% extends "group/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'post:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'group:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'group:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}