group/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'group'

urlpatterns = [
    path('', views.ListGroups.as_view(), name = 'all'),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path('post/in/<slug>/', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name = 'leave'),
]

post/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('post/', include('post.urls')),
    path('group/', include('group.urls'))
]

post/models.py
from django.db import models
from django.urls import reverse
from django.db import models
from django.conf import settings
import misaka
from group.models import  Group
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts", on_delete = models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True, on_delete = models.DO_NOTHING)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "post:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

post/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/post_user_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("post:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

post/templates/post/_post.html
<div class="container">
	<p>{{ post.message_html|safe }}</p>
			<span class="username mr-1"><a href="{% url 'post:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time mr-1"><a href="{% url 'post:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'post:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
</div>

post/templates/post/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends "post/post_base.html" %}


{% block post_content %}
<div class="container">
	<h3>Are you sure you want to delete this post?</h3>

	<div class="posts">
		{% include "post/_post.html" with post=object hide_delete=True %}
	</div>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
		<a href="{% url 'post:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
	</form>

	{% endblock %}
</div>

post/templates/post/post_detail.html
{% extends "post/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "post/_post.html" %}
</div>
{% endblock %}

post/templates/post/post_form.html
{% extends "post/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
<h4>Create New Post</h4>
<div class="container">
	<form method="POST" action="{% url 'post:create' %}" id="postForm">
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" value="Post" class="btn btn-primary btn-large">
	</form>
	{% endblock %}
</div>

post/templates/post/post_list.html
{% extends "post/post_base.html" %}


{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'group:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'group:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>




		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "post/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

post/templates/post/post_user_list.html
{% extends "post/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "post/_post.html" %}
	{% endfor %}
</div>
{% endblock %}