accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name = 'signup')
]

group/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'group'

urlpatterns = [
    path('', views.ListGroups.as_view(), name = 'all'),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path('post/in/<slug>/', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name = 'leave'),
]

post/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name="create"),
    path('by/<username>', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('post/', include('post.urls')),
    path('group/', include('group.urls'))
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Social Network</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Optional theme -->

   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'social_network/css/main.css'%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light" id="navbar">
       <div class="collapse navbar-collapse">
         <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
           <ul class="navbar-nav ml-auto">
             {% if user.is_authenticated %}
              <li><a href="{% url 'post:create' %}" class="nav-link">Post</a></li>
              <li><a href="{% url 'group:all' %}" class="nav-link">Groups</a></li>
              <li><a href="{% url 'group:create' %}" class="nav-link">Create Group</a></li>
              <li><a href="{% url 'accounts:logout' %}" class="nav-link">Log out</a></li>
             {% else %}
              <li><a href="{% url 'group:all' %}"class="nav-link">Groups</a></li>
              <li><a href="{% url 'accounts:login' %}" class="nav-link">Log in</a></li>
              <li><a href="{% url 'accounts:signup' %}" class="nav-link">Sign up</a></li>
             {% endif %}
           </ul>
       </div>
     </nav>
     <div class="container mt-5">
       {% block content %}

       {% endblock %}
     </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Thanks for visiting! Come back soon!</h1>


</div>




{% endblock %}